version: '0.2'
language: en
dictionaries:
  - softwareTerms
  - html
  - css
ignorePaths:
  - node_modules
  - build
  - .docusaurus
words:
  - algolia
  - builtin
  - builtins
  - cspell
  - docsearch
  - inout
  - interop
  - kinded
  - llms
  - macros
  - metaprogramming
  - newtype
  - newtypes
  - nominality
  - nullness
  - numerics
  - overclaimed
  - overclaiming
  - overclaims
  - playwright
  - rethrowing
  - scrutinee
  - signedness
  - soundscript
  - soundness
  - stdlib
  - stdio
  - stringifying
  - subclassing
  - sublabel
  - sublist
  - thenables
  - typeclass
  - tsconfig
  - typecheck
  - typeclasses
  - unlisted
  - userland
  - wasi
  - widenings
  - wordmark
  - valueclass
  - wasm
